### ISSUE TITLE
Allow Multiple Goals to be added at once

### ISSUE THREAD

**Issue by nickdelgrosso** [mrozbarry/mobtime#125]
Hi, 

First, thank you @mrozbarry for this excellent tool!  I'm using it as part of my code dojo events to help introduce programmers to mob programming, and it has been indispensable.  I'd like to give my groups a way to easily insert some pre-prepared starting goals into the timer to help facilitate breakout sessions, and if mobtimer could automatically add multiple goals at once (say, by copy-pasting from a delimited string) it would be pretty straightforward.  

Best wishes, 

Nick

**Comment by mrozbarry** [comment]
Hi Nick, I'm really happy that mobtime is helping your code dojo!

I'm going to have to digest this feature a bit. I like it, I just want to make sure that it can be done in a way that makes sense to a user intuitively, and doesn't break any previous functionality.

**Comment by mrozbarry** [comment]
I sort of understand this as two features (one being the skateboard, the other being the sports car):

## skateboard

 - Add another button called "Add Multiple Goals" that gives the user a `<textarea>` modal where they can add in this text, and previews the new goals
 - This ensures that the original text input doesn't change, since some users may add `;` to their goals and not intend on multiple goals being added
 - This could result in duplicate goals if multiple users attempt to do this, but deleting goals isn't a big deal, either.

## sports car

 - Allow users to create template goals using some other interface on the website
 - Allow users to import template goals/settings in the "Timer Settings" tab
 - Could allow sharing of mob formats (ie default goals, timer length, position names)
 - Could still have the problem of multiple imports

---

That said, I think there's value in this, I just need to make sure that the process of adding multiple goals is smooth to all users.

**Comment by nickdelgrosso** [comment]
That makes a lot of sense.  I guess I submitted a half-a-skateboard approach in #126.  The sports car approach (templates) here sounds good, too, though for my events I'd still have to get them the template somehow.  

I guess if I had a magic wand, it would be to be able to send a "template" or "settings" url that just had the settings pre-loaded (goals, timer settings, and roles) so each group could add their own names and then share their group timer url and get started (the event format has multiple breakout rooms doing the same activity).  Then adding goals one-by-one wouldn't be such a barrier, since it could be done before the event is started and everyone arrives.

**Comment by nickdelgrosso** [comment]
It works great, thank you for adding this feature!  Looking forward to trying it out tonight at my code dojo!

Best wishes,

Nick
